#!/bin/bash
set -e
echo "Training script generated by nnUNet Training Launcher Agent"
echo "=========================================================="

# Configuration
HYPERPARAMETER_REFERENCE_PATH="/home/tianmid1/tianmid1/nnUNet_cust/agent/doc/hyperparameter_reference.json"
TASK_NAME="Task601_TotalSegmentatorV1"
NETWORK="3d_fullres"
TRAINER="nnUNetTrainerV2_configurable"
ROUND_NUMBER=1
SCRIPT_NAME="train_task601_round${ROUND_NUMBER}.sh"
LOG_FILE="nnUNet_training_round${ROUND_NUMBER}.log"

# Step 1: Validate Configuration
echo "[$(date '+%Y-%m-%d %H:%M:%S')] Starting training round ${ROUND_NUMBER}"
echo "[$(date '+%Y-%m-%d %H:%M:%S')] Validating hyperparameter configuration..."

if [ ! -f "$HYPERPARAMETER_REFERENCE_PATH" ]; then
    echo "ERROR: Hyperparameter reference file not found at $HYPERPARAMETER_REFERENCE_PATH" | tee -a "$LOG_FILE"
    exit 1
fi

if ! python3 -c "import json" 2>/dev/null; then
    echo "ERROR: Python3 json module not available" | tee -a "$LOG_FILE"
    exit 1
fi

# Check for active values
ACTIVE_COUNT=$(python3 -c "
import json
with open('$HYPERPARAMETER_REFERENCE_PATH', 'r') as f:
    data = json.load(f)
count = sum(1 for v in data.values() if 'active_value' in v)
print(count)
")

if [ "$ACTIVE_COUNT" -eq 0 ]; then
    echo "WARNING: No active_value found in hyperparameter_reference.json" | tee -a "$LOG_FILE"
    echo "Training will proceed with trainer defaults" | tee -a "$LOG_FILE"
else
    echo "Found $ACTIVE_COUNT active hyperparameter overrides" | tee -a "$LOG_FILE"
fi

# Save command for reproducibility
echo "[$(date '+%Y-%m-%d %H:%M:%S')] Command: $0 $@" | tee -a "$LOG_FILE"
echo "[$(date '+%Y-%m-%d %H:%M:%S')] Hyperparameter reference: $HYPERPARAMETER_REFERENCE_PATH" | tee -a "$LOG_FILE"
echo "[$(date '+%Y-%m-%d %H:%M:%S')] Last modified: $(stat -c %y "$HYPERPARAMETER_REFERENCE_PATH" 2>/dev/null || echo 'unknown')" | tee -a "$LOG_FILE"

# Step 2: Set up environment
echo "[$(date '+%Y-%m-%d %H:%M:%S')] Setting up environment..." | tee -a "$LOG_FILE"

# Activate Python environment (adjust as needed)
if [ -f "/home/tianmid1/miniconda3/etc/profile.d/conda.sh" ]; then
    source /home/tianmid1/miniconda3/etc/profile.d/conda.sh
    conda activate nnUNet
elif [ -d "/home/tianmid1/tianmid1/nnUNet_cust/venv" ]; then
    source /home/tianmid1/tianmid1/nnUNet_cust/venv/bin/activate
fi

# Set nnUNet environment variables if not already set
export nnUNet_raw="/home/tianmid1/tianmid1/nnUNet_cust/nnUNet_raw"
export nnUNet_preprocessed="/home/tianmid1/tianmid1/nnUNet_cust/nnUNet_preprocessed"
export nnUNet_results="/home/tianmid1/tianmid1/nnUNet_cust/nnUNet_results"

# Verify environment
echo "[$(date '+%Y-%m-%d %H:%M:%S')] Python: $(python3 --version 2>&1)" | tee -a "$LOG_FILE"
echo "[$(date '+%Y-%m-%d %H:%M:%S')] nnUNet_raw: $nnUNet_raw" | tee -a "$LOG_FILE"
echo "[$(date '+%Y-%m-%d %H:%M:%S')] nnUNet_preprocessed: $nnUNet_preprocessed" | tee -a "$LOG_FILE"
echo "[$(date '+%Y-%m-%d %H:%M:%S')] nnUNet_results: $nnUNet_results" | tee -a "$LOG_FILE"

# Step 3: Launch training
echo "[$(date '+%Y-%m-%d %H:%M:%S')] Starting nnUNet training..." | tee -a "$LOG_FILE"
echo "[$(date '+%Y-%m-%d %H:%M:%S')] Task: $TASK_NAME" | tee -a "$LOG_FILE"
echo "[$(date '+%Y-%m-%d %H:%M:%S')] Network: $NETWORK" | tee -a "$LOG_FILE"
echo "[$(date '+%Y-%m-%d %H:%M:%S')] Trainer: $TRAINER" | tee -a "$LOG_FILE"
echo "[$(date '+%Y-%m-%d %H:%M:%S')] Fold: all" | tee -a "$LOG_FILE"

# Execute training command
nnUNetv2_train \
    $TASK_NAME \
    $NETWORK \
    $TRAINER \
    --fold all \
    2>&1 | tee -a "$LOG_FILE"

TRAINING_EXIT_CODE=${PIPESTATUS[0]}

# Step 4: Training completion
if [ $TRAINING_EXIT_CODE -eq 0 ]; then
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] Training completed successfully" | tee -a "$LOG_FILE"
else
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] Training failed with exit code $TRAINING_EXIT_CODE" | tee -a "$LOG_FILE"
    exit $TRAINING_EXIT_CODE
fi

echo "[$(date '+%Y-%m-%d %H:%M:%S')] Training round ${ROUND_NUMBER} complete" | tee -a "$LOG_FILE"